# This is a basic workflow that is manually triggered

name: Manual Workflow

# Controls when the action will run
on: 
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "World"
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send Greeting
        run: echo "Hello, ${{ inputs.name }}"
